version: '3'
services:

  kanban-postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB:kanban
      - POSTGRES_USER:kanban
      - POSTGRES_PASSWORD:kanban

  kanban-app:
    build: ./kanban-app
    environment:
      - DB_SERVER=kanban-postgres
    ports:
      - "8080:8080"
    links:
      - kanban-postgres



volumes:
  kanban-data:
